"""As imagens da rodada 1: uma por pagina (e tres do fechamento).
caixa = a parte ampliada (x0, y0, x1, y1, em fracao da pagina)."""

FIGURAS = [
    dict(arquivo="palatino076", base="palatino_p076__inteira", jeito="a",
         caixa=(0.06, 0.12, 0.50, 0.42), camadas=["sumiu"],
         legenda="em vermelho, o desenho da letra S que o jeito de fábrica apagou."),
    dict(arquivo="palatino067", base="palatino_p067__inteira", jeito="a",
         caixa=(0.06, 0.33, 0.50, 0.62), camadas=["sumiu"],
         legenda="em vermelho, o desenho de dentro da letra M que o jeito de fábrica apagou."),
    dict(arquivo="palatino066", base="palatino_p066__inteira", jeito="a",
         caixa=(0.08, 0.79, 0.40, 0.95), camadas=["sumiu"],
         legenda="em vermelho, o que o jeito de fábrica apagou: metade da letra M. do rodapé."),
    dict(arquivo="ljs47-103", base="ljs47_p103__inteira", jeito="a",
         caixa=(0.08, 0.50, 0.86, 0.89), camadas=["sumiu"],
         legenda="em vermelho, os traços do desenho que o jeito de fábrica apagou."),
    dict(arquivo="marial454", base="marial_p454__inteira", jeito="a",
         caixa=(0.0, 0.18, 1.0, 0.74), camadas=["gravura"],
         legenda="em verde, o que o programa achou que era gravura (um remendo de papel e a mancha do verso)."),
    dict(arquivo="antiphon260", base="antiphon_p260__inteira", jeito="a",
         caixa=(0.53, 0.27, 1.0, 0.72), camadas=["gravura"],
         legenda="em verde, a zona que o programa achou como gravura: ela passa por cima das pautas de música ao lado da iluminura."),
    dict(arquivo="pesel021", base="pesel_p021__inteira", jeito="a",
         caixa=(0.0, 0.60, 1.0, 0.93), camadas=[], caixas_olhar=[(0.08, 0.79, 0.90, 0.87)],
         legenda="em vermelho, a legenda impressa no papel escuro: vira tarja preta."),
    dict(arquivo="siebmacher007", base="siebmacher_p007__esquerda", jeito="a",
         caixa=(0.0, 0.60, 0.56, 0.86), camadas=["sumiu"],
         legenda="em vermelho, os pedaços da moldura que o jeito de fábrica apagou e o Preto e branco de sempre guarda."),
    dict(arquivo="horas014", base="horas_p014__inteira", jeito="a",
         caixa=(0.18, 0.07, 0.62, 0.36), camadas=["contou"],
         legenda="em laranja, a moldura dourada e as réguas: é a tinta que faz a página ir para revisar hoje."),
    dict(arquivo="graduale588", base="graduale_p588__inteira", jeito="a",
         caixa=(0.0, 0.26, 0.42, 0.56), camadas=["contou"],
         legenda="em laranja, a tinta fora do texto que faz a página ir para revisar hoje (a letra S azul, as pautas e as notas)."),
    dict(arquivo="graduale222", base="graduale_p222__inteira", jeito="a",
         caixa=(0.0, 0.0, 1.0, 0.42), camadas=["contou"],
         legenda="em laranja, a música (fora das linhas de texto): é a tinta que faz a página ir para revisar hoje."),
    dict(arquivo="palatino010", base="palatino_p010__inteira", jeito="a",
         caixa=(0.0, 0.0, 0.52, 0.36), camadas=["contou"],
         legenda="em laranja, a moldura: é a tinta que faz a página ir para revisar hoje."),
    dict(arquivo="fecho-graduale222", base="graduale_p222__inteira", jeito="c",
         caixa=(0.0, 0.0, 1.0, 0.42), camadas=["sumiu"],
         legenda="em vermelho, o que o 'Só o texto achado' apagou: a música inteira."),
    dict(arquivo="matematica032", base="matematica_p032__inteira", jeito="a",
         caixa=(0.0, 0.55, 1.0, 1.0), camadas=[], cor_caixas="contou", caixas_olhar=[(0.0, 0.84, 1.0, 1.0)],
         legenda="em laranja, a faixa escura do scanner, embaixo: é ela que faz a página ir para revisar hoje."),
    dict(arquivo="boecio007", base="boecio_p007__inteira", jeito="a",
         caixa=(0.0, 0.0, 0.75, 0.26), camadas=[], cor_caixas="olhar",
         caixas_olhar=[(0.11, 0.075, 0.27, 0.20), (0.24, 0.055, 0.78, 0.085)],
         legenda="em azul, a letra Q e os sinais de métrica (- - v v) do alto: ficaram no jeito de fábrica."),
    dict(arquivo="rhetorica034", base="rhetorica_p034__inteira", jeito="a",
         caixa=(0.0, 0.04, 1.0, 0.60), camadas=["gravura"],
         legenda="em verde, o que o programa achou como gravura: fica como no original."),
    dict(arquivo="horas175", base="horas_p175__inteira", jeito="a",
         caixa=(0.17, 0.27, 0.55, 0.47), camadas=[], cor_caixas="olhar",
         caixas_olhar=[(0.225, 0.315, 0.385, 0.415)],
         legenda="em azul, a letra S colorida: o programa não a achou como gravura e ela sai como um bloco preto."),
    dict(arquivo="fecho-boecio007", base="boecio_p007__inteira", jeito="c",
         caixa=(0.0, 0.0, 0.75, 0.26), camadas=["sumiu"],
         legenda="em vermelho, o que o 'Só o texto achado' apagou: a letra Q e os sinais de métrica do alto."),
    dict(arquivo="fecho-escola197", base="escola_p197__inteira", jeito="c",
         caixa=(0.0, 0.06, 0.55, 0.42), camadas=["sumiu"],
         legenda="em vermelho, o que o 'Só o texto achado' apagou: o número 1 e os travessões (—) dos números da margem."),
]
