"""O que eu vi, pagina por pagina, olhando original | jeito A | jeito C | mapa
(06/10/2026). Uma linha por pagina: (A, C, o que se ve).

A = "Guardar a tinta forte" (de fabrica); C = "So o texto achado".
  ok     = saiu certa
  leve   = defeito pequeno, ou o mesmo que o Preto e branco de hoje ja tem
           (figura nao achada sai em preto e branco, beirada do scanner)
  errada = algo impresso sumiu, foi comido pela metade, ou entrou sujeira em cor
"""

VEREDITO = {
    "antiphon_p088__inteira": ("leve", "errada", "A: a capitular B colorida pega um pedaco da pauta vermelha (fica em cor ao lado da pauta preta). C: a musica fora das linhas some."),
    "antiphon_p260__inteira": ("errada", "errada", "A: a zona de gravura cobre pautas inteiras: a musica fica desbotada, como no original, e a borda de folhas sai picotada."),
    "boecio_p003__inteira": ("ok", "errada", "C: a xilogravura e o carimbo somem; so o 'IHS' (que o leitor achou como texto) fica boiando."),
    "boecio_p007__inteira": ("ok", "errada", "C: a capitular Q e os sinais de metrica somem."),
    "boecio_p008__inteira": ("ok", "errada", "C: a capitular O e uma linha de sinais de metrica somem."),
    "boecio_p022__inteira": ("ok", "errada", "C: as duas capitulares Q e sinais de metrica somem."),
    "cursus_p003__inteira": ("ok", "errada", "C: a capitular xilografica e o 'AD' do titulo somem."),
    "cursus_p314__inteira": ("ok", "ok", "So a beirada preta do scanner (corte)."),
    "escola_p007__inteira": ("ok", "ok", ""),
    "escola_p035__inteira": ("ok", "ok", ""),
    "escola_p113__inteira": ("ok", "errada", "C: o 'O' inicial de duas linhas some."),
    "escola_p197__inteira": ("ok", "errada", "C: os numeros '1 -', '2 -', '3 -' perdem pedacos."),
    "graduale_p221__inteira": ("ok", "errada", "C: a musica some."),
    "graduale_p222__inteira": ("ok", "errada", "C: a musica some."),
    "graduale_p223__inteira": ("ok", "errada", "C: a musica some."),
    "graduale_p269__inteira": ("leve", "errada", "A: a borda de ramos sai meio em cor, meio preta. C: pedacos de pauta e notas somem."),
    "graduale_p588__inteira": ("leve", "errada", "A: a capitular azul nao achada sai preta (igual ao Preto e branco). C: musica e capitulares somem."),
    "horas_p011__inteira": ("ok", "ok", ""),
    "horas_p013__inteira": ("ok", "ok", ""),
    "horas_p014__inteira": ("leve", "errada", "A: a moldura dourada nao achada sai preta e grossa (igual ao Preto e branco). C: moldura e reguas da tabela somem ou ficam picotadas."),
    "horas_p016__inteira": ("ok", "ok", ""),
    "horas_p026__inteira": ("ok", "ok", ""),
    "horas_p027__inteira": ("ok", "errada", "C: letras douradas do comeco das linhas somem."),
    "horas_p047__inteira": ("ok", "ok", ""),
    "horas_p175__inteira": ("leve", "errada", "A: a capitular S decorada nao achada sai como bloco preto (igual ao Preto e branco). C: a capitular some, fica um quadrado vazio."),
    "ljs47_p026__inteira": ("ok", "errada", "C: as iniciais azuis e vermelhas somem."),
    "ljs47_p049__inteira": ("leve", "leve", "A pagina inteira virou gravura: manchas impressas em cor."),
    "ljs47_p064__inteira": ("leve", "leve", "Quase toda a pagina virou gravura: manchas da margem em cor."),
    "ljs47_p103__inteira": ("errada", "errada", "A: o diagrama vermelho de tracos finos (nao achado como gravura) fica picotado - somem tracos que o Preto e branco guarda. C: o diagrama some."),
    "marial_p007__inteira": ("leve", "errada", "A: o canto manchado foi marcado como gravura (mancha em cor). C: '& o' somem numa linha."),
    "marial_p454__inteira": ("errada", "errada", "A: um remendo de papel e a mancha do verso foram marcados como gravura: saem impressos em marrom."),
    "marial_p840__inteira": ("ok", "ok", ""),
    "matematica_p032__inteira": ("ok", "ok", "As faixas pretas do scanner (assunto do corte, nao do Misto)."),
    "matematica_p072__inteira": ("ok", "ok", "As faixas pretas do scanner (assunto do corte, nao do Misto)."),
    "opusmajus_p003__inteira": ("ok", "errada", "C: o selo da editora some; sobra 'PRESS' picotado."),
    "opusmajus_p011__inteira": ("ok", "errada", "C: a capitular C some."),
    "opusmajus_p020__inteira": ("ok", "ok", ""),
    "opusmajus_p165__inteira": ("ok", "errada", "C: as linhas dos dois diagramas somem; sobram as letrinhas."),
    "opusmajus_p256__inteira": ("ok", "errada", "C: reguas e numeros da tabela picotados."),
    "palatino_p005__inteira": ("ok", "ok", ""),
    "palatino_p007__inteira": ("ok", "errada", "C: a capitular V e letras do titulo somem."),
    "palatino_p009__inteira": ("ok", "errada", "C: a capitular Q e a moldura somem; sobra um pedaco de fio."),
    "palatino_p010__inteira": ("ok", "errada", "C: a moldura some."),
    "palatino_p057__inteira": ("ok", "errada", "C: moldura, floreios e capitulares somem; sobram pedacos soltos."),
    "palatino_p066__inteira": ("errada", "errada", "A: a letra ornamental 'M' do rodape, de contorno claro, fica pela metade (o Preto e branco guarda inteira)."),
    "palatino_p067__inteira": ("errada", "errada", "A: a capitular xilografica M perde quase todo o desenho de dentro (o Preto e branco guarda)."),
    "palatino_p076__inteira": ("errada", "errada", "A: a capitular xilografica S some quase inteira; fica so a moldura dela."),
    "palatino_p104__inteira": ("ok", "errada", "C: reguas da tabela picotadas."),
    "palatino_p113__inteira": ("ok", "errada", "C: a moldura em pergaminho some."),
    "pesel_p021__inteira": ("errada", "errada", "A e C: a legenda no papel escuro vira tarja preta (o Preto e branco faz o mesmo; nao e do Misto)."),
    "rhetorica_p018__inteira": ("ok", "errada", "C: fios da moldura picotados."),
    "rhetorica_p034__inteira": ("ok", "ok", ""),
    "rhetorica_p073__inteira": ("ok", "errada", "C: chaves e ornamentos somem."),
    "rhetorica_p129__inteira": ("ok", "errada", "C: a gravura de pagina inteira some; sobram 4 letras."),
    "rhetorica_p160__inteira": ("ok", "errada", "C: fios da moldura somem."),
    "siebmacher_p007__direita": ("leve", "errada", "A: moldura de floreios nao achada sai em preto e branco. C: a moldura some."),
    "siebmacher_p007__esquerda": ("leve", "errada", "A: idem. C: moldura e capitular somem."),
    "siebmacher_p009__direita": ("leve", "errada", "A: idem. C: a moldura some."),
    "siebmacher_p009__esquerda": ("leve", "errada", "A: idem. C: moldura e capitular somem; a assinatura fica picotada."),
}
